### ISSUE TITLE
Similar goals as treeplyr?

### ISSUE THREAD

**Issue by richelbilderbeek** [TheoPannetier/phylobates#1]
I wonder if phylobates has the same ideas as [treeplyr](https://github.com/uyedaj/treeplyr).

 * If yes, this will save you quite some work
 * If not, sorry for the noise!

**Comment by TheoPannetier** [comment]
I wasn't aware of `treeplyr`, thanks for showing me this 👍 
The two packages don't do the same thing at all:`treeplyr` links data tables to the tips of phylogenetic trees, `phylobates` is a more general utility package for timetrees, like `ape` or `TreeSim`
